name: "Checkstyle for Java"
# description should be no more than 125 characters!
description: "Run Checkstyle analysis on Java code and report the results directly to the pull request using ReviewDog."
author: "David Bernal"
inputs:
  github_token:
    description: "This is the GitHub personal access token used for authentication. It's required by ReviewDog to report the results of the Checkstyle analysis in the pull request"
    default: "${{ github.token }}"
  workdir:
    description: " This is the current working directory. By default, it's the root directory of the repository."
    default: "."
  excluded_paths:
    description: "Directory/file pattern to exclude from CheckStyle. Multiple excludes are allowed"
    default: ""
  ### Configurations for Reviewdog ###
  level:
    description: "This is the severity level that ReviewDog uses when reporting issues found. Levels can be info, warning, or error."
    default: "info"
  reporter:
    description: "This setting defines how issues found are reported. Possible values are github-check (will create a check review that appears in the PR's Checks tab), github-pr-check (comments will be attached to the PR's code line), and github-pr-review (will create a review on the PR)."
    default: "github-pr-check"
  filter_mode:
    description: "This setting determines how ReviewDog filters results to report. Possible values are added (will report only on lines added in the PR), diff_context (will report only on changes in the diff context), file (will report on all changes in modified files), nofilter (all occurrences will be reported)."
    default: "added"
  fail_on_error:
    description: "his option allows the action's workflow to fail if ReviewDog finds any error. Possible values are true and false."
    default: "false"
  ### Configurations for Checkstyle ###
  checkstyle_config:
    description: "This is the path to the Checkstyle configuration file that defines the set of code style rules to use during the analysis."
    default: "./google_checks.xml"
  use_custom_validations:
    description: "This is a flag to enable the use of custom validations. By default, it's disabled."
    default: "false"
  custom_validations:
    description: "This is the path to the custom validations file that defines the set of custom validations to use during the analysis."
    default: "."
  checkstyle_version:
    description: "This is the Checkstyle version to be used during the analysis. By default, the latest version is used."
    default: "10.18.2"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "check"
  color: "green"